METADATA_EXAMPLES.md
Documentation for good matadata example file.
=> Good Metadata Example file

METADATA_EXAMPLES.md
Referenced the code.gov metadata schema 2.0.0
=> added hyperlink reference to code.gov

CODE_JSON_GENERATORS.md
Documentation for the Code.gov Metadata Schema Code-JSON Generators Tools. 
The document provides a comprehensive tool to access existing generator/scraper tools.
=> Code.gov Metadata Schema Code-JSON Generators Documentation

CODE_JSON_GENERATORS.md
Some of our information was inaccurate, so this corrects that :)
=> Update CFPB project info in CODE_JSON_GENERATORS.md

.github/ISSUE_TEMPLATE/feedback.md, .github/ISSUE_TEMPLATE/questions.md
- Added a feedback issue template
- Added a questions issue template
having issue types for specific questions or feedback can help us get better information from the people submitting.
=> Initial commit of new issue types

CONTRIBUTING.md, README.md
- Updated README.md
- Added CONTRIBUTING.md
=> Docs updates.

data_quality_scoring.md
Added grammatical edits. Slight changes.
=> Updated data_quality_scoring.md

CODE_JSON_GENERATORS.md, METADATA_EXAMPLES.md, README.md
fixed documentation of broken hyperlinks on:
README.md
CODE_JSON_GENERATORS.md
METADATA_EXAMPLES.md
=> correcting broken hyperslinks and Scraper TSF support

data_quality_scoring.md
This pull request is for updated documentation for new Data Quality Scoring Algorithm summary.
=> Update data quality scoring algorithm description

README.md
Added the code-gov-data repo to the projects list under the Contributing header in the README.md file. #39
=> Added code-gov-data to repo list

docs/metadata_examples.md
The relative path has changed after docs folder cleanup addressed in this issue.
https://github.com/GSA/code-gov/issues/54
=> Fixed broken links to images path

docs/CoPMeetingMins/Nov2019.md
Add the link to my slides from GitHub Universe.
=> Add link to slides

docs/CoPMeetingMins/Mar2020.md
=> first edit

docs/CoPMeetingMins/Mar2020.md
=> 2nd update

docs/CoPMeetingMins/Apr2020.md
Added notes to agenda from meeting on 4/16/2020.
=> Updated Apr agenda to meeting minutes

docs/FederalSourceCodeStudy/Series/overview.md
Collection of markdown files to parse out pieces of the FSCS for easier access and reading.
=> Adding series folder and overview doc

docs/FederalSourceCodeStudy/Series/overview.md, docs/FederalSourceCodeStudy/Series/overview_study.md
Content updates for FSCS Series.
=> Content updates

docs/FederalSourceCodeStudy/Series/overview_study.md
Creating Study Overview document.
=> Creation of Study Overview

docs/FederalSourceCodeStudy/Series/overview_study.md
Footnote test and some minor changes.
=> Testing footnotes in overview

docs/FederalSourceCodeStudy/Series/overview_study.md
Update to footnotes and content.
=> Updating content for Study Overview

docs/FederalSourceCodeStudy/Series/history_of_OSS.md, docs/FederalSourceCodeStudy/Series/study_overview.md
=> Content updates to Study Overview and History of OSS files

docs/FederalSourceCodeStudy/Series/history_of_OSS.md, docs/FederalSourceCodeStudy/Series/study_overview.md
=> Updates to Overview and History of OSS md

docs/CoPMeetingMins/Apr2020.md
=> Added link to SPSQ

docs/FederalSourceCodeStudy/Series/history_of_OSS.md
Deleted img, wasn't rendering the way I wanted.
=> Updates to OSS history

docs/FederalSourceCodeStudy/Series/govt_intersection_OSS.md, docs/FederalSourceCodeStudy/Series/history_of_OSS.md, docs/FederalSourceCodeStudy/Series/study_overview.md
=> Govt intersection with oss qa

docs/FederalSourceCodeStudy/Series/govt_intersection_OSS.md, docs/FederalSourceCodeStudy/Series/history_of_OSS.md, docs/FederalSourceCodeStudy/Series/study_overview.md
=> Updating ToC

docs/CoPMeetingMins/Apr2020.md, docs/CoPMeetingMins/May2020.md
=> May CoP agenda

docs/tagging.md
=> Tagging.md

docs/tagging.md
=> formatting edits

docs/FederalSourceCodeStudy/Series/cultural_beliefs.md
Feeding FSCS blog post series.
Closes issue #92
=> FSCS cultural beliefs md file

docs/FederalSourceCodeStudy/Series/cultural_beliefs.md, docs/FederalSourceCodeStudy/Series/govt_intersection_OSS.md, docs/FederalSourceCodeStudy/Series/history_of_OSS.md, docs/FederalSourceCodeStudy/Series/structural_dimensions.md, docs/FederalSourceCodeStudy/Series/study_overview.md
Draft PR for structural dimensions blog.
=> Initializing with structural dimensions
